### ISSUE TITLE
Scenario overlaps the background step

### ISSUE THREAD

**Issue by mazensherif** [danbuckland/crudecumber#7]
The issue is visible running cucumber version that's < 2.0 due to the existing issue that is on crudecumber.

Running a scenario with a background, when the user passes the  background step, the scenario steps overlaps the background. The background should be cleared and display the scenario step.

**Comment by danbuckland** [comment]
Thanks @mazensherif - I'll look into this, sounds like it should be a simple but useful fix!

**Comment by danbuckland** [comment]
@mazensherif this is now fixed in version 0.2.0!
